int8 PROFILE_POSITION_MODE      = 1
int8 PROFILE_VELOCITY_MODE      = 3
int8 HOMING_MODE                = 6
int8 INTERPOLATED_POSITION_MODE = 7
int8 POSITION_MODE              = -1
int8 VELOCITY_MODE              = -2
int8 CURRENT_MODE               = -3
int8 MASTER_ENCODER_MODE        = -5
int8 STEP_DIRECTION_MODE        = -6

uint8 id
int8 mode
---
bool successed
